name: flutter_onfido
description: Onfido plugin for Flutter.
version: 0.1.0
homepage: https://github.com/geweald/flutter_onfido

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.12.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fluencybank.flutter_onfido
        pluginClass: FlutterOnfidoPlugin
      ios:
        pluginClass: FlutterOnfidoPlugin
