name: flutter_onfido_plus
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_onfido_plus_platform_interfaces:
    path: ../flutter_onfido_plus_platform_interfaces
  flutter_onfido_plus_android:
    path: ../flutter_onfido_plus_android  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_onfido_plus_android